### ISSUE TITLE
1.9.4 - The End Monster Mash

### ISSUE THREAD

**Issue by RaineAndrews** [Shinoow/AbyssalCraft#103]
How many zombies are intended to spawn in the End at a time?  Short of bunkers, massive amounts of explosives, and a heart made of cold iron you can't survive the end in it's current state.  I'm talking 40 or 50 zombies swarming the player with unerring ability to see the player no matter where they are.

**Comment by Shinoow** [comment]
The spawn weight for them is 10, which isn't that high of a number. Then again, the only other mob to spawn there is the Endermen (and they apparently have the same spawn weight). Since it's a vanilla mechanic, having a lot of them spawning at once is simply that there's only 2 types of mobs that would spawn there (unless another mod adds something more to spawn there). If they're bothering you, there's a config option that stops them from spawning in the End.
If I am to give a number on how many should spawn at a time, it should be between 1 and 3, then there's the factor of how often the mob is picked to spawn, which might be a 50/50 between that and Endermen.

**Comment by RaineAndrews** [comment]
The problem with so many of them, is their uncanny sense of where the player is.  The endermen loiter, and the zombies swarm.  Mayhaps if only 10% of the spawns were zombies, they would be manageable D:

**Comment by Shinoow** [comment]
It appears their follow range is a bit too big (thought I had turned that down years ago, but maybe I didn't turn it down enough...). One thing here is that the zombies are at 10% spawns, but so is the Endermen, and since the other 80% aren't occupied by any other mob, those 10% each automatically become 50%. Anywho, I could add a config option where you can toggle the spawn weight of the End Abyssal Zombies (and setting that to 0 could replace the current option to disable them from spawning).
