### ISSUE TITLE
[1.7.10] Random event crash

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Shinoow/AbyssalCraft#105]
https://gist.github.com/Shadows-of-Fire/f981c08f5e1dcc43285b9e7bd9b3596c
Any idea what might be causing this?  I realize develoment for 1.7.10 is frozen, but I'd like to see if I can find the cause of this issue.  It appears to be totally random, happening under no certain conditions.

**Comment by Shinoow** [comment]
There's a null checking missing there which has the potential of triggering said crash (and the conditions for the crash to trigger were completely random, so not much there that would point towards something specific). This was dealt with in the other branches, but nobody ever reported it happening in 1.7.10, hence it not getting fixed there.

**Comment by Shinoow** [comment]
Since this will be dealt with in the final bugfix update, I should probably put a bug tag on this...

**Comment by Shadows-of-Fire** [comment]
On a side note, Coralium Plague was invading the potion of leaping from Et Futurum and the Potion of Withering from Ender Zoo.  I'm not entirely sure why, as the potion ids were not conflicting (hence coralium plague showing up properly and applying)

**Comment by Shinoow** [comment]
Yeah, that's due to the limit of potion brewing in 1.7.10 (the bit sequence stuff used to determine brewing recipes are limited to 15 brews, and only 3 of those bit sequences are not occupied by vanilla). I might as well toss in a config option for that (or remove the potion brewing from 1.7.10). The same issue popped up in 1.8.9 (and I removed the brewing hackery altogether there, so that could be arranged for 1.7.10 as well, or be made configurable).

**Comment by Shadows-of-Fire** [comment]
Yeah.  Hopefully that comes with the final fix.  Wither Witches throwing potions that apply both wither and plague are rather strong.

**Comment by Shinoow** [comment]
Another thing with that is that if you were to toss said potion on a entity that is immune to the plague in question, the game will instantly crash, so there's more to that than potion-based butchery.

**Comment by Shinoow** [comment]
The bugfix update is out, thus fixing this issue.
