### ISSUE TITLE
incompatibility with CaveBiomes

### ISSUE THREAD

**Issue by Hypsellis** [Shinoow/AbyssalCraft#106]
I get this crash error when I try to create/load a world when CaveBiomes http://pastebin.com/gtpniUX6. I had already reported this issue to the CaveBiome dev, but he told me that the problem came from AbyssalCraft and not from CaveBiomes. So I report this issue here too.

**Comment by Shinoow** [comment]
The crash report points to pretty much the same stuff as the one in #107, so I don't think AbyssalCraft has anything to do with this one either.

**Comment by Hypsellis** [comment]
Yeah, the Terraqueous bug has been fixed by his owner, but the CaveBiomes owner told me he was unable to solve the problem and that the problem came from AbyssalCraft and not CaveBiomes.

**Comment by Shinoow** [comment]
If you look at the stacktrace in both crash reports, the first couple of lines there point to the exact same code in Terraqueous. Not to mention the version of Terraqueous in both crash reports is the same, I'm pretty sure both crashes might've been caused by that mod (so unless you have a new crash report with the new Terraqueous version, this was caused by the bug in that version).

**Comment by Hypsellis** [comment]
It seems that this bug has been solved in same time that the other bug when ShetiPhian updated Terraqueous. So sorry for the bothering and thanks for your answer. :)
