### ISSUE TITLE
A Plague of Dragons

### ISSUE THREAD

**Issue by Divineaspect** [Shinoow/AbyssalCraft#117]
We're suffering from a plague of dragons which makes the first dimension moderately unplayable.
The dragon's hit boxes are wierdly shaped for being hit vs hitting us, and the immunity to  ranged attacks is aggravating in combination. In addition their flight through the ground makes mining, other then automatically, impossible in that dimension.
Suggested Possible Solutions:
- Have them be repulsed by the portal, as of now they spawn camp.
- A Block type they can't fly through
- Slow them Down
- Some form of talisman, armor, or enchantment, which repulses or despawns them (and a later version to eat them like the elder god you have displaced).

**Comment by Lance5057** [comment]
I play on the same server as Divineaspect, I died 20-30 times just entering the portal to get my stuff as the dragon was just sitting in it and killing me before i even loaded in.

**Comment by Shinoow** [comment]
Well, for starters, they're not supposed to be immune to arrows. If you're encountering a lot of dragons, that's either caused by:
1. The dimension has been loaded for a extended period of time, and nobody has killed any dragons that spawned during this timeframe
2. A mod is increasing the spawn rate of them, making a lot of dragons spawn (instead of maybe a single one)
Since the hitboxes keep coming back as an issue, I guess I'll have to take another look at them, and figure out exactly what's making them not align with the entity.
It could be possible for them to bounce off portal blocks, giving some leverage in cases where one is right by the portal. The ideal case would be to blacklist blocks from being passed through, but since they're set to noclip, that would require a pretty massive alteration to how a noclipped entity is treated by the world.

**Comment by Shinoow** [comment]
The changes in 1.9.4-pre-1 included an overhaul to the dragon hitboxes, making them function correctly (making arrows properly hit them, instead of bouncing about). Other things that have changed since this was initially reported is that they bounce off of portals, spread the Coralium Plague instead of dealing physical damage (however, they still deal half a heart of armor-piercing damage if the Hardcore Mode config option is enabled) and have at some point in the not so distant past had their movement speed reduced slightly (could probably be taken down a little bit more, but at the time some of the movement logic broke at some more extensive alterations). Overall, there should be enough built in functionality to deal with the dragons now.
