### ISSUE TITLE
crash on server (1.9.4) build 1976

### ISSUE THREAD

**Issue by SDUBZ** [Shinoow/AbyssalCraft#120]
theres a mob  causing crashes on my server i later found it was one of your spawners causing it
fml client latest:
[fml-client-latest (2).txt](https://github.com/Shinoow/AbyssalCraft/files/342716/fml-client-latest.2.txt)

crash report:
[crash-2016-07-01_12.18.45-client.txt](https://github.com/Shinoow/AbyssalCraft/files/342722/crash-2016-07-01_12.18.45-client.txt)

minecraft version: 1.9.4
forge:1.9.4 build 1976

**Comment by SDUBZ** [comment]
well luckily setblock is a thing i was able to replace said block but wonder how often this occur

**Comment by Shinoow** [comment]
Closing this issue now. If it's still something that occurs, please re-open it.
Considering this is triggered by something in Zoology assuming the entity the mob spawner spawns is an animal (without properly checking if that statement is true, since this crash occurred), you should probably report it to the issue tracker for that mod, since the only mention of my mod is that it tries to cast one of my entities as a instance of EntityAnimal (which doesn't work, since said entity isn't an animal).
