### ISSUE TITLE
Tiny tiny issue with monolith spawning mechanics

### ISSUE THREAD

**Issue by C0rn3j** [Shinoow/AbyssalCraft#125]
So, an album with this minimalistic issue: http://imgur.com/a/hBq2Q

How to reproduce: place a bunch of statues on the ground along with a chunkloader and return in a few days.

It's noisy.

**Comment by c0rn3j** [comment]
TIL that RFTools Quarry will not mine the statues up. I want to cry.

**Comment by Shinoow** [comment]
Hm... might be about time I add more disruptions, or just remove the one that builds a monolith, since those allow that to happen from a bunch of statues alone.

**Comment by c0rn3j** [comment]
Or perhaps disable monolith building if XX statues are within YY meters next to the statue?

**Comment by c0rn3j** [comment]
Also to anyone dealing with the mess, get WorldEdit, mark the are and run 

//replace abyssalcraft:azathothstatue leaves
//replace abyssalcraft:cthulhustatue leaves
//replace abyssalcraft:hasturstatue leaves
//replace abyssalcraft:jzaharstatue leaves
//replace abyssalcraft:nyarlathotepstatue leaves
//replace abyssalcraft:yogsothothstatue leaves
//replace abyssalcraft:shubniggurathstatue leaves

To get rid of the statues, I had to do it twice since some spawned again.

//replace abyssalcraft:shoggothblock leaves
//replace abyssalcraft:monolithstone leaves

And finally to get rid of the ooze and buildings.

**Comment by Shinoow** [comment]
The monolith building is one possible outcome out of a couple (since there's not that many disruptions, the chances of a specific one triggering is quite large, due to there not being that many other possible outcomes). Currently there's a 6,25% chance that a monolith is built, and the chance of any of the other disruptions triggering is the exact same number (since there's currently 16 of them).

**Comment by Shinoow** [comment]
Closing this, as the disruption mechanic has changed drastically over the past updates, not to mention the fact that the particular disruption that caused this has been disabled for sometime as well.
