### ISSUE TITLE
Statues don't yield PE.

### ISSUE THREAD

**Issue by MentalMouse** [Shinoow/AbyssalCraft#130]
So... I finally got some statues from the shoggoths. I tried holding my Necronomicon near them both on the monoliths and back at my base. I got smoke streams, lightning bolts, and shoggoth spawns (with a monoloth!), but my Necronomicon still shows 0/5000 PE. What am I missing here?  This is with AbyssalCraft 1.9.2.7 and AbyssalCraft 1.9.2.8.  ETA:  On MC 1.9.4/Forge 1976

**Comment by Shinoow** [comment]
This seems to be a case of "did a little thing wrong in a single branch", where a small check was done incorrectly, having the statue expect the Necronomicon to be a statue (since it tries to match the Item to the interface used to determine if a Block is of the type that the statues are). After peeking through the code where this happens, the error only occurs in 1.9.4.

**Comment by MentalMouse** [comment]
I hope you can fix that fairly quickly, but I do have other things still on my shopping list (shadow gems and Liquid Coralium) so I can go chase those in the meantime.
