### ISSUE TITLE
[Suggestion] Adding config info to reduce the size of biomes.

### ISSUE THREAD

**Issue by MidnightBree** [Shinoow/AbyssalCraft#136]
So, I run a private server with some of my friends, and we find that reducing the chance of these biomes spawning doesn't seem to affect them much at all.  We also disabled the chance for us to spawn into the biome, and yet we still get the biomes appearing at spawn.  It wouldn't be so much of an issue if the biomes weren't so large.  Our group also plays with Biomes O' Plenty enabled, and a side-by-side comparison of the generated biomes is a pretty substantial size difference

I'm wondering if there can be an option to reduce the size of the biome generation.  I really want to explore the mod, but not if it takes up half of our map.

**Comment by Shinoow** [comment]
If I was actually in control of the biome sizes, there would likely have been a config option for that implemented 2 years ago.
With the config tweaking regarding biome weights and whether or not a biome should be eligible to spawn in, I assume you generated a new world between each test (as the changes only take effect after a Minecraft restart, and you won't see the change that much if you go back to a world before changing the values until you travel to unexplored chunks). Turning off spawning in the biome doesn't mean said biome can't generate next to the biome you spawn in (which means turning it off won't guarantee a specific biome won't generate close to the spawn biome). To get a better picture of how the biome generation differs when tuning the settings, using the same seed when testing will display variations in biome generation.
In any event, the only biome property regarding any form of size that I've changed (in a few of the biomes) is the height and depth of them. One thing that has a major role in biome sizes are the GenLayers (particularly GenLayerBiomes), which I don't alter in any way.

**Comment by MentalMouse** [comment]
Hmm.  ISTR something about the order of the biomes in their internal list affecting the size of the biomes, with earlier biomes being bigger (IIRC, the Ocean biomes come first).  I don't actually have access to the code, but that's something you might investigate.

**Comment by Shinoow** [comment]
That sounds like pre 1.7 stuff. In 1.7.2 biomes were split into groups based on temperatures (and oceans biomes into their own category), so since that version the temperature-based biomes are split into 4 separate lists based on their category (Desert, Warm, Cool, Icy), while ocean biomes have a separate list.
If need be, the Darklands Forest, Plains and Highlands can all be disabled (as they're pretty much just aesthetic, with the base Darklands and the Mountain more or less being the essentials).

**Comment by MentalMouse** [comment]
Well then.  Maybe you *should* start poking at the GenLayers.

**Comment by jaredlll08** [comment]
@MentalMouse few questions
1) Are you a coder?
2a) If the answer to 1 was Yes, then make a PR.
2b) If the answer to 1 was No, then listen to what @Shinoow says because changes are, he knows more about this than you do.

**Comment by Shinoow** [comment]
After digging deep into the code regarding biome generation and biome sizes, I've reached the conclusion that I will not make biome sizes for my biomes configurable. The main reason for that is the fact that the biome size is a single value used for every biome the world attempts to generate (meaning I'd either have to add my own WorldType just to implement a configurable restriction for my Overworld biomes, or do some hacky stuff directly to the vanilla class that assigns the size), then there's also the fact that mods that allows you to alter the biome sizes (among other things) already exist.
The reason BoP biomes are smaller is because their WorldType contains a system that allows you to configure just about anything in each separate biome they add (that includes setting different biome sizes for different biomes, resulting in those biomes being bigger or smaller depending on what size they've been set to).
BiomeTweaker is a mod which has the ability to change biome sizes, and it can be found here: https://minecraft.curseforge.com/projects/biometweaker

**Comment by MentalMouse** [comment]
OK,  that does sound like you're better off leaving the tweak to a mod that's specialized for the purpose.  Thanks for checking it out!

**Comment by MidnightBree** [comment]
@Shinoow 

"... mods that allows you to alter the biome sizes (among other things) already exist."

That would have been helpful to mention.  I didn't know you could reduce the size of modded biomes with additional mods.  I'll look into that.
