### ISSUE TITLE
[Bug?] Crystallized Cluster chest spawn

### ISSUE THREAD

**Issue by drakray** [Shinoow/AbyssalCraft#137]
As of now, only Crystallized Zinc is available to find in chest, out of the 25 available.
Is this voluntary?

**Comment by Shinoow** [comment]
The reason why that's the only one found in chests is that unless there's a mod present that adds in Zinc (or Brass, since Brass is a copper-zinc alloy), it's pretty much impossible to obtain Zinc in a crystallized form. Might eventually have more crystals showing up as loot when there's more use to them (the Materializer is getting closer to being fully implemented, among things).

**Comment by drakray** [comment]
Ah ok, didn't understand since I always use Metallurgy or Base/Modern Metal lol
No use keeping that open, as it's Intended Behaviour
