### ISSUE TITLE
Asorah spawning then immediately despawning

### ISSUE THREAD

**Issue by Prodigy1189** [Shinoow/AbyssalCraft#140]
i have tried to summon Asorah 3 times in the Abyssal Wasteland. He spawns for about a split second before vaporizing into a cloud of smoke. I'm not sure what the problem is as it is not on peaceful. Hopefully you can provide some insight. If you need anything from me to help figure out the problem let me know. On a smaller note is Sacthoth's Soul Reaper Blade supposed to be unenchantable? and what happens when you harvest 1,024 souls? provided you even harvest that many before it breaks

**Comment by Shinoow** [comment]
It would be useful if I could get the Minecraft version, Forge version and AbyssalCraft version of your instance. There's only two scenarios I could think of that could affect the spawning, those being:
- You didn't have enough PE when performing the ritual (but Asorah wouldn't spawn at all if this was the case)
- J'zahar was for some reason present in the same dimension, and banished Asorah (this is a very unlikely scenario, which would only trigger if someone had spawned J'zahar there, since he only spawns at his temple)

The sword is meant to be unenchantable, that is intentional behavior.
When the soul counter reaches specific numbers (32, 64, 128, 256, 512, 1024), you get healed and receive some aiding Potion Effects. It appears I haven't written down the effects anywhere (apart from the source code itself and a reply in the MCF thread), so I'll dig up the list and post it here:
```
32:
Strength I (30 seconds)

64:
Strength I (1 minute)

128:
Strength II (1 minute)
Speed I (30 seconds)

256:
Strength II (1 minute)
Speed I (1 minute)
Resistance I (15 seconds)

512:
Strength III (1 minute)
Speed II (1 minute)
Resistance I (30 seconds)
Fire Resistance I (15 seconds)

1024:
Strength III (2 minutes)
Speed III (2 minutes)
Resistance I (1 minute)
Fire Resistance I (30 seconds)
Saturation I (15 seconds)
Health Boost III (2 minutes)
```

**Comment by Prodigy1189** [comment]
yeah, neither of those two cases were true in my case, i had more than enough PE, and i've never messed with J'zahar before. Anyway i use minecraft 1.10.2, forge 12.18.1.2039, and abyssalcraft 1.10.2-1.9.2.5   ..............................that's the only version of forge that all my mods work correctly on, all but this one problem with asorah

**Comment by Shinoow** [comment]
Using the versions provided, I was still unable to reproduce it. The ritual spawned the boss as expected, without any despawning.

**Comment by MCJediYoda** [comment]
I had this problem when I was either in creative mode or not enough pe.  I go into survival mode and ensure I have 10000 pe I think it is and I have no issues.

**Comment by jameshforster** [comment]
Just to revive this slightly, my server is having the same issue as part of a modpack using:

Forge 2125
SpongeForge 2123

Given that it works on SSP but not on SMP I would be inclined to believe it was due to SpongeForge (a server only mod) which is an issue we have seen before with other mods. I don't know whether you want to investigate this or whether this is outside your normal work due to compatibility with other mods. So yeah, just for information.

**Comment by Shinoow** [comment]
Sounds like this should be taken up with the Sponge devs (since SpongeForge is part of their server framework).

**Comment by Shinoow** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1003#issuecomment-266171873
There seems to be a built in thing in Sponge that prevents anything with a bounding box larger than a specific set of bounds from spawning.
