### ISSUE TITLE
Check on spawning rates for Lesser Shoggoth

### ISSUE THREAD

**Issue by AlphaKintari** [Shinoow/AbyssalCraft#143]
I have a base near a beach, and even though it's said that the spawning rates are really low, I've seen about 6 or so spawns, including 2 on the same night which the ooze really wrecked my base.  

Suggestion - have the ooze despawn after a bit, I like the mechanic, but it's really easy to have a base totally get destroyed by it.

**Comment by Shinoow** [comment]
The spawn rates are really low, but beach biomes is one of the biomes that they have a chance of spawning in.
I'll need a bit more info on the despawning. Since blocks don't despawn (closest thing to despawning is leaves decaying), the ooze could turn into dirt or something after a certain period of time has passed.

**Comment by AlphaKintari** [comment]
My base is on a peninsula so it might just be the RND curse.
Turning to dirt would be a big improvement.  Maybe once the light level gets to a certain point?

**Comment by Shinoow** [comment]
The current in-dev implementation has a config option, that when activated makes the block attempt to convert into dirt every 200 world random ticks (and the conditions are a random number check with a 10% chance of success and a check of nearby light where the minimum light level is 13, so having a light source nearby or being in broad daylight will make it turn into dirt). Might do some tuning on the light level, but this would enable the ooze to dissolve on it's own. Since light behaves differently in other dimensions, this might be limited to worlds that have a day/night cycle until I've balanced it out for unnatural light.

**Comment by AlphaKintari** [comment]
That sounds perfect.  Might not need too much balancing in non-over world dimensions - how often would someone put a main base in another dimension?  Maybe a small one for protection, but those should be able to be fixed easily.

**Comment by Shinoow** [comment]
Yeah, and I didn't take into account that the artificial light used in some dimensions (among them all of the AbyssalCraft dimensions) doesn't count as actual light, so any ooze spread there won't dissolve unless you place a light source nearby.
