### ISSUE TITLE
Asorah does not spawn spectral dragons

### ISSUE THREAD

**Issue by mrtopf** [Shinoow/AbyssalCraft#151]
From what I read Asorah is supposed to spawn some dragons. That does not happen though. Not sure if it's a inter mod issue though as I also have Rough Mobs installed (which maybe is the reason why the wasteland is so full of zombies and skellies).

**Comment by Shinoow** [comment]
That's never been a thing. Way back the dragons spawned more frequently (compared to them pretty much never spawning now with their spawn rates obliterated), making them a thing to keep track of while fighting Asorah. Since they no longer spawn at the frequency they used to, they don't really contribute to the fight at all.

**Comment by mrtopf** [comment]
Ah ok, got it. The book says "uses spectral dragons" so I assumed he spawns them. But that explains it then, thanks! (there is no way to up their rate again via config, is there?)

**Comment by Shinoow** [comment]
There isn't anything built in to change the spawn rates (then again, isn't there a billion mods that allows you to alter spawn rates of things?). The use part is that Asorah drains the health of them to heal himself.

**Comment by mrtopf** [comment]
Yeah, I misunderstood this part :-) And I will try to change spawn rates with rough mobs then as I am not sure there are really that many mods out there which can control spawn rates in 1.10.2 or I overlooked them. So thanks again.
