### ISSUE TITLE
information about statues

### ISSUE THREAD

**Issue by Efimero** [Shinoow/AbyssalCraft#164]
currently,the entries about statues in the Necronomicon do not mention that the statues need to be under open sky to be able to operate
this should be mentioned (or changed so they don't need sky) to avoid confusion
also, it is unclear that they work when NOT on top of soggoth monoliths (though it is correctly stated, the way it is phrased can lead to confusion)

**Comment by Shinoow** [comment]
The change that they require a clear sky was added shortly before releasing 1.9.3, a while after everything else included in that update had been documented, so any documentation on that specific detail is currently no present in any way.
Considering there are multiple screenshots of them not being placed on monoliths (including ones where they're transferring PE), there should be enough evidence that they don't require the monoliths in order to operate, but that could be emphasized more.
