### ISSUE TITLE
[1.10.2] Crash on load when used with Gregtech 5 Unofficial

### ISSUE THREAD

**Issue by MechanosG** [Shinoow/AbyssalCraft#165]
I first reported it on the GT5 github here, complete with crashlog - https://github.com/Blood-Asp/GT5-Unofficial/issues/731

They immediately closed it and said it was on AbyssalCraft's end, so I'm reporting it here instead.

**Comment by Shinoow** [comment]
I'd say it's GT's fault for adding meta values surpassing the 16 limit vanilla has in place for blocks, but since they're not gonna change that, I'll just have my code ignore meta values above the allowed bounds.

**Comment by Dragon2488** [comment]
>It isnt GT issue. Item Damage and Block Metadata are different things. It's related both to AbyssalCraft and to BOP. Ore item damage doesnt equal to ore in world metadata. It's two different things, understanding them as same isnt always right. So it's ususual case when item damage of ItemBlock is used not as block metadata. And again, IT ISNT GREGTECH ISSUE!

**Comment by Shinoow** [comment]
Apart from the world.setBlockState() part, pretty much the same code (since the crash occurs while attempting to fetch the state). I'm adjusting my code to be in par with the BoP code (since they applied a fix that stopped the crashing). If it continues after that version has been released, there's not much more to do on my end (unless I add a metadata threshold on what blocks it will try to fetch a state from). Hopefully, that won't be the case, and everything will work like it should after I've done the change on my end.
