### ISSUE TITLE
Dimensional Spawnlist Purge Isn't Working

### ISSUE THREAD

**Issue by Viatos** [Shinoow/AbyssalCraft#175]
I am using Minecraft 1.10.2, Abyssalcraft 1.9.3.8, and Forge 12.18.2.2166. I have the config option set to purge and then recreate dimension spawnlists for AbyssalCraft. 

Using Mo' Creatures (WITHOUT Custom Mob Spawner, which keeps your dimensions from spawning anything except shoggoths), a number of mobs seem able to spawn in all dimensions despite the config. HorseMobs (skeletal, zombie, and bat-winged horses), silver skeletons, and wraiths make sense in the Abyssal Wasteland, since they're tagged as undead (actually I don't know about the bat-winged ones) but chimerae and Fire Ogres of all things are a little immersion-breaking - and I've found Fire Ogres and wraiths in the Dreadlands, and Fire Ogres and chimerae in Omothol.

Other mobs from that mod aren't spawning in your dimensions (no bunnies, no scorpions), and as far as I can tell no other mod-added mobs do. I thought maybe you whitelisted anything tagged as undead and chimerae and Fire Ogres are just incorrectly tagged by Mo' Creatures, but I don't see skeletons past the Abyssal Wasteland, so it can't just be an undead exception, right? I would like these mods to play together (unless you intend to add rideable night-gaunts/Mi-Go/polyps) nicely, so if there's anything you can think of I'd really appreciate it. If I can't find a fix I'll disable Mo' Creatures, but I'll be sad about it - as horrific as its fake config and bundled CMS can be, riding wyverns is pretty awesome.

**Comment by Shinoow** [comment]
I haven't done any whitelisting in terms of mob spawning, but the biomes are set to a single biome type in the Biome Dictionary (not doing this would result in it making guesses on what types would fit on the biomes, then set those biome types, which in turn would allow even more mobs to spawn if they've been set to spawn in biomes using those types).
The reason the Mo' Creatures mobs still spawn is because they're registered after my purge code has run (apparently all the mob registration is done in post-init in that mod). I could see if I can squeeze in the purge to run at a later phase (I recall seeing something that's run after post-init, but before server start).
Those mobs are spawning there due to them being set to spawn in biomes tagged with DEAD in the Biome Dictionary (which I've tagged all of my dimension biomes with).

**Comment by Viatos** [comment]
Okay, thank you, that helps a lot. I appreciate the information and the consideration; in the meantime I'll take another run at CMS and see if the devil can be dealt with after all. Can't believe they set FIRE OGRES to spawn in dead biomes...ugh.
