### ISSUE TITLE
J'zahar not dropping Essence of the Gatekeeper

### ISSUE THREAD

**Issue by luckdemon** [Shinoow/AbyssalCraft#177]
Playing with modpack All the Mods Expert V1.06 which is using Abyssalcraft 1.10.2-1.9.3.8
After killing J'zahar (have done so twice now), the first time I stood back from the blast and got no loot except for experience, the second time, I stood right in it and got sucked through and received no loot or experience, but did get the teleport and debuffs (which I cured with milk). Am I doing something wrong, or is this fight bugged?

**Comment by Xiaoyan366** [comment]
Yes, we also did not loot
The falling loot is
(ImmersiveEngineering) skin package

In the server 2 people have been explosive suction
Start the transfer and it will crash
Only one person will not collapse
[crash-2016-12-25_15.24.33-server.txt](https://github.com/Shinoow/AbyssalCraft/files/672218/crash-2016-12-25_15.24.33-server.txt)

**Comment by Shinoow** [comment]
@Xiaoyan366 That crash is triggered by Extra Utilities 2
```
at com.rwtema.extrautils2.items.DemonicIngotHandler.getRawStack(DemonicIngotHandler.java:53)
at com.rwtema.extrautils2.items.DemonicIngotHandler.onJoin(DemonicIngotHandler.java:40)
```
Something there doesn't like that a custom Item Entity is spawned (since a custom Item Entity is used in order for the essence to float mid-air, as opposed to falling down).

@luckdemon I haven't tested in expert mode, but regular ATM crashes (with the same Extra Utilities 2 stacktrace as in Xiaoyan366's crash report). Depending on how far away you were, you might've been outside of the range (48 blocks), as if no player is within that range J'zahar makes the assumption any player got pulled into the Dark Realm.

**Comment by Shinoow** [comment]
I appear to get the same Extra Utilities 2 stacktrace in ATM Expert as well (version 1.0.19).

**Comment by Shinoow** [comment]
No crashes with 1.9.3.10, update/ask the modpack maker to update their pack(s) to that version.
