### ISSUE TITLE
[Consultation] TPPI3C integration

### ISSUE THREAD

**Issue by Baughn** [Shinoow/AbyssalCraft#181]
I'm evaluating Abyssalcraft for an upcoming modpack (TPPI3C). There hasn't been time enough to get further in than the bare basics, but I have some questions I hope you can answer.

In particular, I'm worried about any mechanics which would affect a server as a whole, e.g. setting the weather to rain or thunder when that isn't a local phenomenon, something which the spotlight suggests that one of the divine sculptures do.

That's a general concern. Anything with such effects needs to be either limited to affecting just Abyssalcraft, localized, or otherwise not likely to affect any players who may not be interested in Abyssalcraft at all — that is, unless the specific purpose of the mechanic is affecting *other* players. I'd accept a config option for it, of course.

There's also the worldgen, some of which to be quite honest is rather ugly, and destructive; I'd prefer to not have anything in the overworld which can destroy someone's base without, again, them poking the mod at all. I did find a config option to disable the shoggoth lair spawns in the overworld, but would doing so block out part of the mod? If it's only needed to gain materials for certain recipes, then I think we'll be fine.

Can't speak for the biomes yet, but I think we'd want to make them rare.

As a catch-all... is there anything else you think we'd want to know, particularly in relation to balancing?

**Comment by Shinoow** [comment]
There's nothing in the mod that changes the weather (well, apart from the one ritual that allows you to change the weather in the current biome you're in), so there shouldn't be any problems with that.

The main purpose of the lairs is finding large amounts of Lesser Shoggoths, thus allowing you to obtain statues from them building monoliths, so the lairs can be disabled at the price of having to do a bit more work in order to obtain statues (then again, 1.9.3.5 came with a bunch of new structures generating in Darklands biomes, including a few shrines that has a chance of generating with a statue inside them). I plan on adding a config option to disable Lesser Shoggoths spawning in the Overworld at all (since right now they have a small chance of spawning in a select few biomes, without any configurability on that). If the amount of lairs generating is considered to be too much, you can change the rarity of them generating in the config.

If need be, half of the biomes can be disabled without if affecting the mod (only possible effect would be that less of them generate, since half of them would be disabled), so as a bonus to reducing the chance of them generating, the Darklands Plains, Forest and Highlands biomes can all be disabled.

**Comment by Shinoow** [comment]
Closing this. If any questions would arise at some point, either ask them here or file a new issue (in case it's not on the same topic).
