### ISSUE TITLE
Darkstone does not properly report its harvesting tool

### ISSUE THREAD

**Issue by JaSpr** [Shinoow/AbyssalCraft#190]
getHarvestTool returns null. This messes up The One Probe (it shows "No tool" required, although this is not true), and while Waila Harvestability gets it right, it does so through series of tests that could return false results under the right circumstances.

https://github.com/McJty/TheOneProbe/issues/133

**Comment by Shinoow** [comment]
The same likely applies to a ton of vanilla blocks as well (then probably a bunch of modded blocks too), since the harvest tool is only set on a few specific blocks, while most don't have it set there. Since some harvesting tool mechanic aren't working on a few blocks, I'm probably going to set the harvest level on the majority of those that currently don't have one set.

**Comment by JaSpr** [comment]
As a note, a pull request was accepted yesterday fixing the issue in TOP, although explicitly setting the harvest tool is always a good idea.

**Comment by Shinoow** [comment]
Yeah, since vanilla has hardcoded the tools for specific materials (where there's a few edge cases in which the tools checks for the block material rather than a harvest tool or if the block is in the hardcoded range).
