### ISSUE TITLE
Insane spawning of Spectral Dragons

### ISSUE THREAD

**Issue by BSKCorp** [Shinoow/AbyssalCraft#202]
I run a small private mod pack server and one of my friends who is big on playing with Abyssal Craft says the waste land is over populated with the dragons. Like an insane amount. I have went in and looked myself and they all over the place. I have tried the purge monsters in the config, restarting the server. I have found no settings to lower the spawn rates for these and it is becoming a rather large problem. I have counted close to 20 of these dragons near where he spawns at and he can not get more then a few blocks before almost dying. Is this intended or is it something else. Any help would be great.

**Comment by Shinoow** [comment]
The Spectral Dragon is the entity with the lowest spawn rate of the entire mod, at the very limit on how low a spawn rate something can have without explicitly modifying the spawn mechanic as an attempt to lower it more. Either you have a mod present that's boosting the spawn rates (or just altering them in general), or nobody has been bothered to kill any spawned dragons (since mobs tend to stick around if you don't kill them, and nothing despawns if the dimension it's inside is unloaded).

**Comment by Bastiondar** [comment]
Did BSKCorp ever resolve this? I'm playing a new modpack that was released about 5 days ago, and the same thing is happening. Except they are spawning in the Overworld. I'm trying to find out how or where the modpack creator is increasing their spawns rate, but can't seem to find it. What's the Spectral Dragon's entity name or id? Thanks.

**Comment by Shinoow** [comment]
abyssalcraft.dragonminion or abyssalcraft:dragonminion (if you're in 1.11.2, otherwise use the former). The only dimension they spawn in naturally is the Abyssal Wasteland, so if they're spawning anywhere else it's because someone has configured them to.

**Comment by Bastiondar** [comment]
Ok, thanks, appreciate it.
