### ISSUE TITLE
[Bug] Crystallizer going over max stack count

### ISSUE THREAD

**Issue by BloodWorkXGaming** [Shinoow/AbyssalCraft#207]
Goes over 64 and then wraps around to -127 again
http://prnt.sc/f1eizr

Missing max Stack Size check in this line: 
https://github.com/Shinoow/AbyssalCraft/blob/master/src/main/java/com/shinoow/abyssalcraft/common/blocks/tile/TileEntityCrystallizer.java#L300

**Comment by Shinoow** [comment]
The Stack Size check is done here:
https://github.com/Shinoow/AbyssalCraft/blob/master/src/main/java/com/shinoow/abyssalcraft/common/blocks/tile/TileEntityCrystallizer.java#L281

But the logic above needs some tuning so that it doesn't return true until the stack size check. Couldn't get it to wrap in my dev env, just kept incrementing the stack size (while it continued to showed 64).

**Comment by BloodWorkXGaming** [comment]
Ah missed that line, sorry ^^

The wrapping was in 1.10, that might have changed something

>

**Comment by Shinoow** [comment]
Could be that 1.11.2 handles the wrapping differently, resulting in the stack size increasing without it visually looking like it is (as I ran my test in 1.11.2).

**Comment by BloodWorkXGaming** [comment]
Time to wait for 1.10 not being a thing anymore then I guess :P

Shinoow <notifications@github.com> schrieb am Do., 27. Apr. 2017, 13:43:
