### ISSUE TITLE
[1.11.2 - 1.9.4-pre-2] cascading worldgen lag crash

### ISSUE THREAD

**Issue by Boodaflow** [Shinoow/AbyssalCraft#208]
After starting up a new world, I started exploring near the spawn point until a sudden crash.
This issue seems to involve several mods including: Embers, Inventory Pets, AbyssalCraft, Recurrent Complex, Astral Sorcery, denseores, and Roguelike Dungeons.

[15:09:08] [Server thread/WARN]: AbyssalCraft loaded a new chunk (-21, 12  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

I tried posting the log in zip, but it wouldn't upload.

**Comment by Boodaflow** [comment]
capnkirok of Inventory-Pets seems to have the solution:

https://github.com/capnkirok/Inventory-Pets/issues/170

**Comment by Shinoow** [comment]
If you're actually getting a crash from this (other than log spam), it'd be great if you posted that. As for the log spam, this issue was already handled in 1.9.4-pre-1, but some specific ore generation code wasn't properly set up, resulting in that particular bit still causing some cascading worldgen lag. It's already been addressed in my workspace, and will be handled in the next release.

**Comment by Boodaflow** [comment]
I'm assuming since the lag was so great due to so many mods involved, the game crashed before the log could finish resulting in an incomplete logging of the instance. However, if that is the case, then you can go ahead and close this and thanks for getting back to me.
