### ISSUE TITLE
Demon Animal - mod compat

### ISSUE THREAD

**Issue by Seth0067** [Shinoow/AbyssalCraft#213]
This is, quite possibly, an unreasonable request, but it would be great if the demon animals were implemented in such a way that you can use these mobs with animals from other mods.  

In my case, I'm thinking "Animania" but perhaps there's a way to do this in such away that you can enter a mob id in the AC config and it applies "demon animal" effects to pretty much any other creature or mob.  

Like I said, possibly unreasonable, but could be cool and will extend the possibilities for modpack creators.

Thanks, Shinoow, for the great work on this mod.

**Comment by Shinoow** [comment]
If you're talking about automatically creating demon variants of things in this proposed list, that would be a bit more than I'm willing to put out for a feature like this (then there's also all the handling code, which would likely be composed of assumptions, with every potential to break due to missing custom properties, or other things thereof).
I could set up something to simulate the effect (eg. have a list where you declare the ID of a mob, then the ID of a demon animal, and it will spawn the specified demon animal when the mob dies, following the same conditions used for the evil animal -> demon animal transition, possibly injecting some AI tasks to make the mob hostile towards players, if not already).
If it's specifically meant to apply for already existing demon animals, then consider it done, otherwise the scope might need some tuning.

**Comment by Seth0067** [comment]
Hey Shinoow - 
Sorry - missed the notification on yr response.

Yeah the scope is totally up to you.  :)  Whatever is easiest.  I'm just looking for a way to use Animania with your mod in a way that allows for demon animals but that doesnt require me to enable vanilla mobs along with the Animania variants.  

To make sure I understand, from the user perspective, the user would:
1) See a friendly Animania cow. 
2) Cow passively looks on as cows do. 
2) Player kills cow
3) Demon cow (using current vanilla-ish model) spawns to hunt player to his/her doom.  

Do we lose the vanilla animals aggresively menacing the player without being specifically aggro-ed?

If its easy to do, would love to try it out, regardless!

**Comment by Shinoow** [comment]
That would be the expected result. The "possessed" bit where the hostile animals go against you right away wouldn't be a thing here unless this would also hook into the AI, inserting a task to turn them hostile (of course, not having that present would greatly increase the chance of catching the player by surprise). Since I add fake animals to hide among the real ones, they get weeded out quite rapidly if someone were to replace the normal ones, so a system to simply tell the game to spawn a demon animal of choice when the specific animal dies (possibly having some randomization to it, so it might not always spawn the demon variant, thus making it potent to really catch the player off-guard).

In order to limit it to demon animals only, the format would probably be something like this:

`modid:mobname:0`

Where the `modid:mobname` bit is the ID for the mob, whereas the integer represents the demon animal to spawn (instead of providing two IDs, allowing you to do this conversion with any entity combination, which could be a interesting feature, but is outside the scope here).

An alternative would be to add a decimal number afterwords, making it:

`modid:mobname:0:0.2`

So `modid:mobname` would have a 20% chance of spawning demon animal 0 on death.

I might use semicolons to separate the different bits of it, to more easily distinguish what is what (mainly due to the entity IDs differing between 1.10.2 and 1.11.2, whereas 1.10.2 doesn't use the `modid:mobname` format). There would likely be a default spawn chance applied if that bit isn't specified, making it optional to specify if there should be a specific spawn chance, or just do it every time.

**Comment by Seth0067** [comment]
Sounds great!  Let me know if I can help/test in any way!
