### ISSUE TITLE
Game freeze when returning from Abyssal Wasteland

### ISSUE THREAD

**Issue by BaccarWozat** [Shinoow/AbyssalCraft#220]
Using Forge 2315, Abyssal Craft 1.9.4-pre4, and perhaps importantly, the [Cubic Chunks](https://github.com/OpenCubicChunks/CubicChunks) mod (current build is 0.0.615.0).

Went into the Abyssal Wasteland from Y=526, dimension loaded and worked fine, but upon returning (from Y=71) the game seized up, not crashing (no crash report) but not doing anything. I suspect it will do this if returning from any AbyssalCraft world to any location out of vanilla bounds.

FML Client Latest log (if needed): https://www.dropbox.com/s/v92yd6zc6aowro6/fml-client-latest-abyssal.log?dl=0

![2017-06-11_01 13 46](https://user-images.githubusercontent.com/8357501/27008934-08556a74-4e46-11e7-9021-abe6849e9452.png)
![2017-06-11_01 17 53](https://user-images.githubusercontent.com/8357501/27008935-09f5aaec-4e46-11e7-9ebc-0361895d9bfc.png)

**Comment by Barteks2x** [comment]
It's probably another issue with teleporter class...

Basically, vanilla has no easily reusable code for transporting players between dimenssions, each mod has to copypaste it. And by default it scans from the top of the world down tp y=0 to find suitable portal location. I can workaround it by changing the max height the mod receives, but it still won't work 100% correctly.

**Comment by Shinoow** [comment]
I could add some hooks on my end for the max and min height, like integers in the API package. Something like that could open up for some compatibility on this.

**Comment by Barteks2x** [comment]
You would need to use completely different code that finds portal position.

The problem isn't that the mod doesn't know the max height, the problem is that it tries to iterate all the way up from it, down to zero. And the max height is an insane value - `Integer.MAX_VALUE/2`.

Instead, the mod should scan only N blocks around the player vertically, for some N, at least when cubic chunks is installed. 

I know it's unlikely many mods will do it, so I will modify my `getActualHeight` method to return some more sane value based on generator settings, but it will mean it will be possible that the teleporter won't find any portal above certain height threshold, and more importantly - below y=0. But at least it won't freeze the game completely.
