### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by MinecraftPlaye** [Shinoow/AbyssalCraft#237]
Whenever someone throws a Dreadium Katana Sword to the ground, he gets kicked from the Server with the following message:
https://pastebin.com/T9X7Yk6J

Minecraft 1.11.2
Forge Mod Loader version 13.20.1.2454 
AbyssalCraft Integration-1.11.2-1.5.0
AbyssalCraft-1.11.2-1.9.4-pre-4

**Comment by Shinoow** [comment]
Following the stacktrace, that's caused by Tech Reborn. The stacktrace points to https://github.com/TechReborn/TechReborn/blob/1.11.2/src/main/java/techreborn/events/OreUnifier.java#L61
where the error happens due to the if statement above (https://github.com/TechReborn/TechReborn/blob/1.11.2/src/main/java/techreborn/events/OreUnifier.java#L60) not actually detecting an empty ItemStack (you're supposed to invoke ItemStack.isEmpty() rather than referencing ItemStack.EMPTY, as that doesn't cover all cases where it's considered empty).
