### ISSUE TITLE
[1.12.2]Dreadland Energy container weird numbers

### ISSUE THREAD

**Issue by Gayanfalor** [Shinoow/AbyssalCraft#249]
Hello, i'm playing atm3 v 5.2,

i have made a dreadland energy container to store Pe but when i look into it it says -11000/240 000, but when i break it and look tooltip it says 114 000/240 000

![2017-12-05_20 19 37](https://user-images.githubusercontent.com/10771109/33626263-5fc20958-d9fa-11e7-84df-2ae6b1010b01.png)

**Comment by Shinoow** [comment]
Does it continue to display that number if you place it down once again and look at if after breaking it? This is something that can happen due to the number representing the contained energy being "too big" (which in this case is anything larger than 32767), but I haven't encountered it myself. Has this happened with other tiered energy containers?

**Comment by Gayanfalor** [comment]
i updated to atm3 5.3 and break the container its still showing the weird number, i didnt tried with previoustier so i cant tell if its doing it too

**Comment by Ncrpts** [comment]
Confirming this is happening to me on a sevtech server, on the same dreadlands energy container
