### ISSUE TITLE
Abyssal Wasteland altar doesnt form 

### ISSUE THREAD

**Issue by tigerdan2** [Shinoow/AbyssalCraft#256]
only tested on MP 
AbyssalCraft-1.12.2-1.9.4.3.jar
The  altar in the wastelands does not form.
Followed a tutorial and also tried nearly any block from abyssalcraft (every coralium/abyssal stone type)
https://streamable.com/5uqn4

**Comment by Shinoow** [comment]
Not sure what tutorial you've been following, but the altar is made from Abyssal Cobblestone or Coralium Cobblestone.

**Comment by tigerdan2** [comment]
yeah
tried both
https://streamable.com/lrzba
Abyssal cobblestone does not work
but it did work with Coralium Cobblestone.
thanks

**Comment by Shinoow** [comment]
The reason it wasn't working is due to there being some Shoggoth Ooze in close enough proximity to the blocks. This is something the next release of the mod will change, as rather than checking for air blocks around the blocks to be the altar and pedestals, it'll check for things that are either air or plants, layered snow and other blocks that aren't full cubes (which in turn will make the altar creation less tedious when things like that are around where you intend on building the altar).
