### ISSUE TITLE
1.12.2 Abyssalcraft and custom mob spawner

### ISSUE THREAD

**Issue by Sersaypygan** [Shinoow/AbyssalCraft#259]
#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.1.2600
- AbyssalCraft: AbyssalCraft-1.12.2-1.9.4.3

Not a crash or random bug, but i'v noticed an overall issue where Darklands spawns are being blocked from appearing entirely. This was an issue in both single player and on a server, and the issue was narrowed down to mo creatures with it's required custom mob spawner, similar to the problem with #258 . Looking at the previous issue however, dosint really solve it however as the poster's problem was fixed randomly on its own.

I wanted to know how exactly one would go about making the mobs spawn again, and if messing with json files is required, how to do such. The last time I was adding mods, configuration was a much easier, simpler case of simply clicking global mod settings and turning an option on or off. I have 0 experience in json files and commands, and 0 understanding of such.

As for determining custom mob spawner as the problem mod, I used the method of simple deduction of active mods, finding that with all other mods installed, and custom mob spawner removed, your mod's creatures where allowed to spawn. If you need to see something like a log however, where would I go to get that for you? As this is also something I have 0 knowledge in.

**Comment by Shinoow** [comment]
Custom Mob Spawner is incompatible with just about any mod adding either mobs or biomes (can't say the mob adding one is certain, but considering CMS pretty much wipes any mob spawning table for biomes that doesn't have default configs, probably). If CMS really is a hard dependency for Mo' Creatures now, you'll be forced to manually add all mob spawns back (which requires altering the JSON files in the CMS config folder), otherwise you should be able to uninstall CMS, then Mo' Creatures will just use whatever default spawning it has for it's mobs when CMS isn't present.
As for editing the JSON files, that comes down to how the files are structured, something that could probably be discovered by observing how the mod handles the vanilla biomes.

**Comment by Sersaypygan** [comment]
Thank you for the reply. I had discovered in single player it was possible to remove CMS and still have all mobs spawn, but the removal of such in a server list seems to immediately crash the server. It sounds so much something that shouldint be your problem to handle if CMS is indeed so incompatable. Thats on them, not you. I'll inform the server owner to remove the mod one more time just to see if we can manage it without that mod.

If you dont mind me asking, where would I look to see how mod handles the vanilla biomes? In CMS's own .jar?

**Comment by Convergence2738** [comment]
Here, check this out: This is basically how CMS works: http://www.mocreatures.org/forum/m/13290502/viewthread/19961817-cms-instructions. 

You can literally manipulate ALL of the mob spawns via this thing. You just go into the config for CMS and go at it. Each dimension has its own spawn lists, so if you want to mod the spawns of creatures. Make sure to go to the proper dimension first as config changes listed in another dimension do not apply to others. The problem with CMS and a good number of biome adding mods is that the mobs usually aren't added right. With Abyssalcraft, it is glaringly obvious as the biomes added by the mod are literally empty, but the vanilla biomes mob spawns are untouched and properly added in. If you have the time, you can manually add in all the right biomes into the configs. I am doing it myself right now, so I'll come back and comment again if my Herculean Task works. On a sidenote, if you think this is bad, forestry and botania are extra cringe as they add stuff that ends up going into the Abyssal dimensions. (experimented in creative mode to see how bad it was)

**Comment by Convergence2738** [comment]
After trying to wrangle the blasted thing. I have found it's either: A) CMS cannot recognize custom blocks and thus cannot spawn entities on them or B) your biome ID's aren't syncing into the configs for CMS well. After bashing my head against a wall for over 8 hours. I am more willing to say it's option A.

**Comment by Shinoow** [comment]
I've only really looked into the CMS configs at one point (I want to say around MC 1.5 or maybe 1.6), and from that instance I've just resorted to staying away from it. If you're looking for ways to alter mob spawns, Mcjty's In Control is the way to go (or Just Another Spawner if you're still in 1.7.10).
If you're forced to use CMS, then well... have fun with that, as I can't provide any information on anything in regards to configuring my stuff with it (as it has a custom biome format differing quite from what other mods use in order to identify specific biomes), nor do I intend on ever getting a grasp on how it works.

**Comment by Convergence2738** [comment]
Wow, Never even knew 'In Control' existed. It's basically like JAS and doesn't derp with spawns like CMS does. Interestingly enough, people are also noting problems getting In Control to work with Abyssalcraft as well. It's something to do with the biome ID's. https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2785031-in-control#c20.

**Comment by Shinoow** [comment]
That post is 5 months old, not to mention the poster didn't have correct JSON syntax on the biome part, as that's meant to be an array rather than a single string.

**Comment by Convergence2738** [comment]
Ok, if I wanted to do something similar and control a mob spawn (namely, exclude a mo' Creatures mob from lets say: the Abyssal Wasteland). I'd need to generate a command array with the correct biome ID?

**Comment by RexMontag** [comment]
Well that explains why the Wastelands are barren except for occasional Shog lairs. Also why the Glacidus keeps spawning skelly knights instead of... ice mooses or whatever are supposed to be there.

Am I to understand that MoCreatures should still work more or less even without CMS? I've read elsewhere that MC doesn't need CMS anymore, but it's still listed as necessary one the MC dl page... anyone know for sure?

Thanks!

**Comment by Convergence2738** [comment]
Mo' Creatures works just fine without CMS. Though.. the spawns get weird without it. You will start getting bat horses, ogres, and what not in the Abyssalcraft dimension biomes. So you lose the immersion without CMS, but at least things will spawn in the Abyssalcraft biomes. I would recommend 'In Control" if that bothers you as you can tweak the spawns for Mo' Creatures WITHOUT having another mod gut vanilla spawning and ruin the spawns completely for custom biomes. THough, it going to require you getting clever with the In Control config. 

Here is In Control and the guy that lists his tweak config data for Abyssalcraft biomes. You should get a sense of what to do from it. Second post down, the fellow is Terpo. https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2785031-in-control?page=2

**Comment by RexMontag** [comment]
I already get MC spawns in the Nether, Twilight Forest and the Hunting Dimension, and zero spawns in the Abyssal Wastelands and the Misty World. As mentioned, in Glacidus I get pretty much just skeleton knights for some reason.

It sounds like even with In Control it's gonna be a lot of work to tweak each dimension, but I'll take a look, thanks for the link!

**Comment by RexMontag** [comment]
UPDATE: I removed CMS and now I get Abyssal Wasteland spawns just fine (as well as some MoCreatures spawns there). 

Now I'm realizing how easy I had it exploring the Wastelands with no mobs @_@''' I might put it back just so I can mine in peace >_<
