### ISSUE TITLE
[1.12.2] Greatly increased mob spawns/no despawning in Abyssal Wasteland

### ISSUE THREAD

**Issue by Vyraal1** [Shinoow/AbyssalCraft#263]
#### Description:

Greatly increased mob density in Abyssal Wastelands, doesn't seem to be a limit on the mob spawns.

https://streamable.com/2tywk

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 2613
- AbyssalCraft: 1.9.4.4

#### Latest log file for when the issue was present:

N/A (I'll try to get another server log soon)

**Comment by Shinoow** [comment]
Horses don't naturally spawn in that dimension. Either track down which mod it is that's set them to spawn there and alter whatever config they might have, or enable "Purge Mob Spawns" in the AC config, which should remove them from the spawn table.

**Comment by Hjaldar** [comment]
For anyone coming here from the future, this behavior was caused by the mod roughmobs. It gives skeletons and zombies a chance to spawn on a skeleton or zombie horse. This behavior can be disabled in the roughmobs config or spawn limits can be enforced with In Control!

This issue can probably now be closed.
