### ISSUE TITLE
AbyssalCratf[1.12.2]: Can't read the names of the blocks and some other stuff!

### ISSUE THREAD

**Issue by PaulWeider** [Shinoow/AbyssalCraft#266]
When I installed this mod I noticed some stuff has mysterious names. I don't know if it's one of the features of this mod but it's difficult to search this items in NEI or something else.
<img src="https://i.imgur.com/6UIcPut.png">
<img src="https://i.imgur.com/FPqUnFB.png">
Pls help!

**Comment by Shinoow** [comment]
That's a new feature added in 1.9.4.4, tied to the knowledge system that's being integrated further into other parts of the mod. If you're just checking things out in creative, you can run `/acunlockallknowledge` to unmask everything, otherwise item/block names are unmasked as you progress further into the mod (the knowledge system is currently mainly rooted in exploration and mob killing, so by exploring biomes/dimensions and killing various mobs unlocks the required knowledge to see the item/block names)

**Comment by PaulWeider** [comment]
Ahhh Thank u ! I was afraid of something crash!

**Comment by Xyzer376** [comment]
Only Work when cheat enabled
