### ISSUE TITLE
[SevTech] AbyssalCraft Mob Spawn Issue/Limits

### ISSUE THREAD

**Issue by EhGneissGuy** [Shinoow/AbyssalCraft#285]
## Issue / Bug

First off, using the same layout I did for [my post over at SevTech](https://github.com/Darkosto/SevTech-Ages/issues/2158). If my understanding of this is off, please let me know. I'd be happy to remove both posts.

AbyssalCraft mobs target vanilla/non-abyssalcraft mobs, kill them, equip the drops, and then go on to pile up and not respawn. If these areas remain loaded, the mob cap is presumably hit and mobs don't spawn at all. Went nearly three hours without a hostile mob spawn before we found multiple pile ups like this.

![2018-04-30_00 50 09](https://user-images.githubusercontent.com/17113297/39415516-49f297ac-4c12-11e8-9910-595d0c41f1a5.png)

![2018-04-30_00 54 24](https://user-images.githubusercontent.com/17113297/39415544-953efa66-4c12-11e8-89e1-d15ba2d06cfc.png)

![image](https://user-images.githubusercontent.com/17113297/39415851-01e484bc-4c16-11e8-9a4d-a869f962a3eb.png)

## Expected Behavior

Unfortunately, this is as expected. However, as the mobs kill everything around them, they shouldn't even be able to pick up items as this is a walking traffic jam.

## Possible Solution

Make AbyssalCraft mobs unable to pick up mob drops/items.

Purge AbyssalCraft mobs periodically - start of each day or after they've been alive for a day unless named.

## Steps to Reproduce (for bugs)

1. Spawn AbyssalCraft mobs.
2. Spawn vanilla hostiles.
3. Let ACM kill vanilla hostiles.
4. Let them pick up drops inadvertently.
5. Behold, they never go away.

## Context

Incredible decrease in mob spawns. Went from non-stop attacks to seeing one zombie in about three hours of play.

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.171
* Launcher Used: ATLauncher

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost, 4GB, Premium
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?: No

**Comment by Shinoow** [comment]
My mobs don't attack any nearby mob they encounter (except for the Anti-Players, as they have a chance of attacking anything that isn't themselves, not to mention Lesser Shoggoths that go after any animal they come across). What's happening is an Abyssal Zombie killing a regular Zombie, which then drops Rotten Flesh and Bones (a lot of things besides Skeletons drops Bones in SevTech). which then gets picked up by anything nearby that can pick things up.

There are already configurable item blacklists in place to stop this behavior from happening (a lot more common in the Abyssal Wasteland due to no restriction on mob spawning allowing both normal and Abyssal Zombies to spawn just about anywhere).

I've provided the necessary changes to Darko and Necron, so this will be fixed in 3.0.7.
