### ISSUE TITLE
[Request] Option to disable the Shoggoth acid projection braking blocks

### ISSUE THREAD

**Issue by Fireztonez** [Shinoow/AbyssalCraft#286]
The new feature added to the Lesser Shoggoth, to added spitting acid make shoggoth incenlly difficult to kill and this is anoying and killing Shoggolth is necessary to advence in nthe modpack I made now.

Can you please add option do just disable the fact of breaking blocks with his acid, like that is not impossible to kill them without a freaking OP stuff!!

Version: 
Minecraft: 1.12.2
AbyssalCraft: 1.9.4.8
Forge: 14.23.3.2678

Thank's
Fireztonez

**Comment by Shinoow** [comment]
You don't really need OP stuff to kill them, unless you intentionally crank up the difficulty, in which case any mob will be tougher than it usually is. A shield can soak up all the acid, not to mention close combat, since they only spit when you're far away enough from them. The block hardness required to prevent being destroyed by acid is already configurable, so apart from that you only need acid-resistant materials to more or less nullify it (or come up with a better strategy than to try and cheese them from a distance). Some aspects of the projectile will be tweaked in the next update, along with how frequent the shoggoths spit acid.

**Comment by LordHellscream** [comment]
this feature is getting so much hate from folks, abyssal craft is essentially the most hated mod in SevTech mod pack (this being one of the reasons).
In general any kind of griefing (block breaking) is poor design, not to mention this attack even destroy graves.

**Comment by choekstr** [comment]
It's really a case of sevtech requires abyssalcraft progression VERY early, like stone age with stone tools and leather armor.  Even if you do it with the most powerful armor at the very early stage, with iron or bronze armor, you get 3 shots from the acid on normal difficulty and you are dead.  Normal difficulty, not intentionally cranking it up, not trying to cheeze it, just stay alive long enough to get a pillar to spawn to get a statue.  

People have been resorting to blocking them in the lair and killing them for the flesh instead of doing the tower/statue mechanic.  This new acid mechanic is fine if one has a kitchen sink pack and OP armor early on, but for progression packs, ie sevtech, it is near impossible to progress without cheating and/or cheezing.  

And lastly of course with TombManyGraves the acid destroys the grave and all items are lost.  The proverbial insult to injury.  Noted the block hardness as a way of potentially fixing this.

Ideally a config setting to change frequency of spits, turn on/off spitting, damage of each spit ball, etc would be great @Shinoow.  Appreciate the support and help as I love this mod and want others to as well.

**Comment by Fireztonez** [comment]
@choekstr In the lastest version of AbyssalCraft the dev already add multiples options about the acid projection of the shoggolt. Now the Shoggolt Acid can be block by shields, and you can change the block hardness the minimum block hardness acid can break... So, personally I think, if you learn how the mob and the acid work, this is possible to kill Shoggolt without die 1000 times!

@LordHellscream Block Breaking is part of Minecraft and I think is not always a bad thing... But I agree the fact of breaking grave is an issue... I don't know if in Sevtech, the grave can be destroy by shoggolth, I don't think the acid can break that type of grave... But I think, this should be great to have way to black-list manually somes blocks in the settings, to make sure the grave can't be delete and give possibility to blacklist certain blocks...

**Comment by LordHellscream** [comment]
Creeper only break block when it's next to you and targeting you. Shoggoth can break block all on itself without player anywhere near it, this kind of grieving is (in my humble opinion) a poor design. 

I have a beautifully decorate underground recharging altar (with partially open ceiling for statues) on a beach biome I have not used for a long time and a couples days after the update I found half the place got wrecked with gooes everywhere, I was no where near there for the entire time.

I had to spent better part of my day (hours) to rebuild the entire room with monolith stone (not to mention the time to hunt down the materials for it).  This kind of thing really ruins the experience for me.

I think Shoggoth should not be able to break block unless it's attack a player and the player is nearby (like the creeper).

**Comment by choekstr** [comment]
Set the block hardness to 0, it breaks logs, cobble, anything I tried but monolith stone from the lair itself.  Tried 2.1, as stated as the minimum in the config file, seemed to be the same.  According to block hardness in MC on the Wiki the minimum it will break is everything but obsidian in vanilla or iron/gold/diamond blocks.  

I had full bronze armor, bronze shield (best available for period), Totemic rituals with resistance 4, strength 3, and they still wrecked me over and over trying to block them in their lair, wrecked me in the water since they can swim faster than us with the shield up and without the shield you die pretty quick, and they wrecked me on land since shield only protects forward and you walk slower with it up and blocking the slime and the shogoths will easily get to the side and bypass the shield.  

I guess there are 2 types of people: Those who say "git gud ya scrub" and those who actually understand game mechanics, what makes for balanced play, and who understand that not everyone has access to server configs, and that OP mechanics added to a mob isn't fun when you have to have kite 6 mobs and try to block devastating acid from multiple directions.  Just my opinion and feedback that echos the multitude of

**Comment by Thrakk** [comment]
In relation to AbyssalCraft with SevTech the Shoggoth's are super lame. You can't run from the spit because of the black goo and you're supposed to get close to them so they can move around, spread goo, and build towers. Sure you can alternately get the statues by killing them but crafting the statues is lame and efficiently killing them just encourages a 1 block wide (2-3 deep) crevice underneath them (preferably at their nest because they cant break monolith stones) and there's nothing epic about fighting cheaply like that. Running around and fighting them wouldn't be bad if the goo didn't slow you down. Basically getting them to build all the towers you need takes a long time and I ended up using creative mode. I don't think you can even get a shield at that point in SevTech.

**Comment by RobertLSnead** [comment]
It appears that they are able to shoot through blocks also, even their lair blocks.
They seem to still fire up close and acid is not being absorbed.
Very difficult to kill these creatures.
