### ISSUE TITLE
[Suggestion] Add Config Controls for World Gen in Other Dimensions

### ISSUE THREAD

**Issue by MokahTGS** [Shinoow/AbyssalCraft#288]
I'd like to create a modpack where the overworld isn't used and the player starts in another dimension.  Currently I don't see a way of configuring Abyssalcraft's world gen to do it in another dimension besides the overworld.

I'd like to see a way to add world gen structures, biomes, creatures to other dimensions via their IDs in the configs.  This would allow modpack makers tremendous freedom in creating worlds.

**Comment by Thiana** [comment]
Seconded. I think the mod overworld biomes are rather out of place but would work really nicely in places like the Deep Dark or Nether.

**Comment by Shinoow** [comment]
All of the overworld generation checks for the Overworld world provider, so any dimension-adding mod can have those things generate inside their dimension(s) provided they use that world provider.
Overall, these kind of configs aren't really within the scope of the mod.
Mob spawning could be implemented, but then you might as well use a mod dedicated to that, like [In Control](https://minecraft.curseforge.com/projects/in-control?gameCategorySlug=mc-mods&projectID=257356), specifically designed to give you free hands at customizing mob spawning.
For structures, [Recurrent Complex](https://minecraft.curseforge.com/projects/recurrent-complex?gameCategorySlug=mc-mods&projectID=223150) allows you to create (or recreate) structures to generate in the world. As mentioned before, if you can get a custom dimension to use the Overworld world provider, and have the right biomes in it, the structures and whatnot will generate there by default.
Adding biomes to existing dimensions is not doable in a simple enough manner to just reduce it to a list in a config file, primarily due to it requiring either usage of ASM or Reflection to straight up overriding the dimension in question to add multi-biome support, which could be nullified by another mod also overriding the dimension. At this point you're better off using something like [Just Enough Dimensions](https://minecraft.curseforge.com/projects/just-enough-dimensions?gameCategorySlug=mc-mods&projectID=254317) to create a custom dimension with the biomes you want to have generate there.
