### ISSUE TITLE
Missing localization name

### ISSUE THREAD

**Issue by mcBegins2Snow** [Shinoow/AbyssalCraft#309]
Description:
Screenshots
![2018-08-05_18 39 39](https://user-images.githubusercontent.com/37864486/43685139-eeaf4a00-98df-11e8-9fb9-f09eaa1b5352.png)
The tipped arrows who come from AbyssalCraft don't have own localized name:
```
tipped_arrow.effect.Cplague
tipped_arrow.effect.Dplague
tipped_arrow.effect.Antimatter
```
![2018-08-05_18 40 13](https://user-images.githubusercontent.com/37864486/43685141-ef0ca218-98df-11e8-86a9-63411804ed4c.png)
The Transmulator fuel and Crystallizer fuel's JEI interface don't have own localized name:
`gui.jei.category.fuel.burnTime`
Crash report:
Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge:14.23.4.2747
- AbyssalCraft:1.9.4.11

**Comment by Shinoow** [comment]
The reason the tipped arrows aren't localized is mainly because I didn't want them to exist in the first place (but there doesn't seem to be any Forge hook for that AFAIK). If you fire an arrow tipped with a Potion of Annihilation, you'll quickly realize it tears through anything in second, which is the main reason why I don't want that (or my other potion effects for that matter) attached on arrows.
