### ISSUE TITLE
AbyssalZombie overspawn/chunkloading

### ISSUE THREAD

**Issue by CatRabbit499** [Shinoow/AbyssalCraft#319]
#### Description:
When running AbyssalCraft, logs spammed with duplicate UUID conflicts for abyssalcraft:abyssalzombie
(even when nobody is on the server, therefore the assumption of chunkloading by not saving on unload)

#### Crash report:
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: `minecraft_server.1.12.2.jar`
- Forge: `forge-1.12.2-14.23.4.2757-universal.jar`
- AbyssalCraft: `AbyssalCraft-1.12.2-1.9.4.11.jar`

#### Latest log file for when the issue was present:
https://gist.github.com/CatRabbit499/d86f91eab13bdcbf214650e6f6d85c8a

**Comment by Shinoow** [comment]
That's likely due to them killing regular zombies, then picking up their drops (mostly rotten flesh), which in turn prevents them from despawning. There's a section in the config file for item blacklists used to prevent mobs capable of picking up stuff from picking up specific items. I plan on setting this as the default values in the config file:
```
minecraft:rotten_flesh
minecraft:bone
abyssalcraft:antiflesh
abyssalcraft:corflesh
abyssalcraft:anticorflesh
```
