### ISSUE TITLE
Uncontrolled spawns around chunk loaded portals grinds the game to a halt.

### ISSUE THREAD

**Issue by MuteTiefling** [Shinoow/AbyssalCraft#327]
#### Description:

I'm opening this properly with the template, even though there's been a report since May that was never deleted, despite not following the template: https://github.com/Shinoow/AbyssalCraft/issues/290

The issue is simple. It would appear that DreadSpawn (and other dread mobs) can spawn automatically around a Dreadlands portal. This in and of itself isn't problematic. What is problematic is that they seem to continue to spawn and multiply when no player is within normal spawning ranges. Indeed, it happens even when no player is in the dimension. All it requires is that the portal be chunk loaded.

In my case, I had set down a remote RS network right by my portal and chunk loaded it so I could access my stuff as I progressed. When I finished with the dimensions, I left all that there thinking I may come back later for something. Oops! 

By the time I discovered the issue, I had 9500 entities spawned in the chunks surrounding the portal. The game was unplayably laggy outside of the dimension, but once I entered the dimension, all hope was lost. I could no longer move and the game would eventually run out of memory. This is the one and only screenshot I was able to capture:

![9k entities](https://user-images.githubusercontent.com/9543430/46472642-d748af00-c7ab-11e8-809c-8ca95f2048fd.png)

As you can see, the issue was compounded by the fact that the mobs were getting killed by coralium, meaning I had item drops to deal with too. I have the feeling this was also causing them to multiply faster...

Suggested fixes include disabling portal spawns when no player is in the area, despawning mobs when no player is in the area, and setting a hard cap on the number of these specific mobs that can be spawned at once due to the fact that they seem to divide and spread on their own...

#### Crash report:

This does not directly cause a crash. It just leads to the world crashing due to there being too many entities.
----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.4.2707
- AbyssalCraft: 1.9.4.9

#### Latest log file for when the issue was present:

I have no logs. It just lead to my game halting instantly upon loading the game. Again, too many entities.

**Comment by choekstr** [comment]
This isn't limited to around the portal.  In my case I had statues and PE collector that caused the uncontrolled game breaking spawning.  I had to stop collecting PE after 10 minutes since the spawns would be out of control.  I can stay there and continually kill the mobs (good for drops) and that keeps them under control but if I don't they multiply out of control.  

I do have dread plague infested chunks there and that might be the issue?  That'll learn me for using dreadium for a Tinkers sword blade. Now everything that spawn, even coralium mobs are getting red sparkles from the dread plague.

I might try moving the statues and collector to a new area to see if I can get back to playing with AbyssalCraft
