### ISSUE TITLE
The staff of Rending

### ISSUE THREAD

**Issue by kreezxil** [Shinoow/AbyssalCraft#336]
Originally posted on my World of Dragons pack issues tracker of which I am the developer.

AbyssalCraft's Staff of rending and its subsequent upgrades does not harvest energy from abyssal mobs even tho it damages them and kill them.

to collect energy from the staff you right click with the staff in your hand and the crosshair on the abyssal mob

Minecraft: 1.12.2
Forge: 14.23.5.2806
Mod: 1.12.2-1.9.4.14

reference: https://github.com/kreezxil/World-of-Dragons/issues/33

**Comment by ShinduPurpleCrystal** [comment]
You need to be in the Abyssal Wasteland for it to work

**Comment by daodragon** [comment]
The problem was caused by scaling health and forge creating an issue in which weapons were in a state that didn't loose any durability, get exp ( tinkers' construct ) , get energy (abyssal staff) and it also caused the ender dragon and the spectral dragon becoming invulnerable.

Forge build 2807
ScalingHealth-1.12.2-1.3.32-134
