### ISSUE TITLE
Bug report collection. Of multiple Bugs!

### ISSUE THREAD

**Issue by SirAron111** [Shinoow/AbyssalCraft#358]
Bug report collection. Of multiple Bugs!

Ok Bug number one The Dragon Boss gets stuck on nothing and just flaps around on the same spot letting you kill him easy. He is even more useless than the Ender dragon since he doesn’t spit any fireballs or so. (He could learn a bit from the chaos guardian from draconic or at least stop getting stuck on nothing)

Going into the portal (any portal) breaking it on the abyssal dimension side and placing a new one to get out you can’t get back into the portal from the over world even if you make a new one until by chance a mob walks into the one on the other side or you restart the server/single player.

If no dimension is set for the jzhar black hole skill it will simply cause a crash. You should fix this or make an option for the boss to use a special dimension for the teleport (a new one where the player has to get out of a labyrinth or something funny) since getting ported to dimensions like dimensional doors ones is buggy af and if the player ends up in the spectra dimension or the quantum quarry dimension this isn’t much fun. So in modpacks you have to use the blacklist and if you blacklist all the skill just crash the game.

Biomes spawn way too much to balance the dark biome spawning out in a world that uses bioms o plenty or even normal I had to turn off all biomes other than the Cswamp and the normal dark lands and even setting them to 1 for spawn chance causes every 4 biomes to be one of these. (Way to much)

At the end a small enhancement idea of mine. Fior the bosses:
Dragon Boss should be a bit faster and ram the player a bit more. As well as get a ranged attack.
Dread Boss shouldn’t spam so many minions and instead go into hiding ocasionaly spaning big hands and mouths that lash out from the walls etc. (tentacle stuff XD)
Jzhar: less floppy auto attacking or random insta kills give him some magic let him shoot beams from his staff sometimes or make other stuff than that big black hole or the buggy suck in skill.
Thx for reading hope some can be fixed

GZ: SirAron

Forge 14.23.5.2836 (and lower (so on most of them))
AbyssalCraft-1.12.2-1.9.7.jar
Minecraft 1.12.2
Modpack: Dimension Zero (and the mod alone also tested still happens)

**Comment by Andromander** [comment]
Now for a collection is issues in this issue...issueception.

1. You did not follow the issue template provided. Always use what is given to you for more concise bug reporting.
2. Do not report multiple issues in 1 ticket. Each issue should be reported into their own ticket, so that when the individual issue is fixed, only that ticket can be closed and not the whole report. Same can be applied opposite: if the individual issue is fixed and the others aren't, then keeping the ticket open isn't tracking fixed issues.
3. Issues and suggestions are completely separate reports, don't lump them together in the 1 ticket. Then again, this point is moot because issues should be individually reported.
4. The issue regarding biome generation cannot be fixed. This is due to the randomised nature of biome generation, so the reason for "too many" of the Darklands biomes is because of random luck.
5. Asorah being "more useless" than the Enderdragon is an overstatement. Without Asorah, you cannot progress AbyssalCraft (just a nitpick, but worth noting that using hyperbole in issue reporting is rather informal).

**Comment by SirAron111** [comment]
https://youtu.be/l-iJpWcsx6Y?t=6325 kk i will make seperate issues but have a look at the tame dragon while i do so XD sry
