### ISSUE TITLE
Sacroth Missing !this.world.isRemote Before Setting Nightime

### ISSUE THREAD

**Issue by jredfox** [Shinoow/AbyssalCraft#365]
Sacroth Missing !this.world.isRemote Before Setting Nightime onInitialSpawn. This causes issues with anything trying to render it on client side making the time equal to night then flashing back to what the server says it is as it should be. So please fix your check there. It also would mess up on client side a few ticks to by simply spawning one in initially when it is daytime. This isn't silkspawners job to correct night/daytime nor re-add any broken blocks bosses would do because any data manipulation should be done on server side

**Comment by Shinoow** [comment]
Judging by this report on [the Mojang bug tracker](https://bugs.mojang.com/browse/MC-114019),  I shouldn't have to check sides in that method, as it's meant to be server side only (but ``MobSpawnerBaseLogic`` improperly calls it on the client side). Seeing as your mod overrides ``MobSpawnerBaseLogic``, wouldn't it be more appropriate if you removed the part where it invokes ``EntityLivingBase#onInitialSpawn`` on the client side, rather than every mob-adding mod that might do something in that method putting side checks (you might wanna use some ASM to patch the vanilla mobs as well if you choose not to fix the vanilla bug in your version of ``MobSpawnerBaseLogic``)?

I would question why someone would even put a boss mob in a mob spawner, but there's nothing stopping someone from doing such a thing, so that question would cancel itself out.

**Comment by jredfox** [comment]
I call EntityLivingBase#onInitialSpawn so it accurately renders the mob. So skeletons have their bows. You should have to check if world is remote because it is a two sided event. On Client side it constantly switches between day and night so just insert the !world.isRemote and it will fix it.

**Comment by Tamaized** [comment]
Since it's AbyssalCraft, having the rapid day/night sounds like a feature to me.

**Comment by jredfox** [comment]
issue is not invalid the client side onInitialSpawn can and will fire by both me and other mods this issue is on your side not other mods

**Comment by jellysquid3** [comment]
@jredfox The contract of the `EntityLiving#onInitialSpawn` method is that it is only called on the server. This is well established and every other mod upholds this contract. MC-114019 represents a bug with Minecraft violating this very contract (evident by vanilla implementations not checking the world's sidedness -- they expect it to only be called on the server-side).

It is not the responsibility of other mod developers to workaround this error on Mojang's part. If you are writing your own mod and choosing to follow this _broken behaviour_, then your mod itself is _**broken**_.

**Comment by jredfox** [comment]
It is not only called on the server side many client rendering calls it to give entities their armor

**Comment by jredfox** [comment]
Go ahead and launch vanilla minecraft mob spawners 1.12.2 They have the skeleton equipment enabled and called EntityLivingBase#onInitialSpawn proof this is not server side only without any other mods

steps to reproduce:
`/setblock ~ ~ ~ mob_spawner 0 replace {SpawnData:{id:skeleton}}`

**Comment by Shadows-of-Fire** [comment]
@Shinoow you may want to lock this issue

**Comment by Shinoow** [comment]
> You will also get fired from real world coding jobs and can't keep a job for this crap.

Funnily enough I am in the process of quitting a real world coding job, but the reason for that isn't because I refuse to follow broken coding conventions (it's more in line with depression and other things related to that).
Anyways, since the conversation in this issue is completely one-sided, and destructive, I'm locking this issue to prevent that from escalating even more.
