### ISSUE TITLE
Dungeon generator with world type amplified

### ISSUE THREAD

**Issue by G1R-Productions** [Shinoow/AbyssalCraft#386]
#### Description:

Surface dungeons generate extremely rarely when using amplified world gen setting.

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2815
- AbyssalCraft: 1.9.5.2

**Comment by Shinoow** [comment]
Can you be a bit more specific. Exactly what do you mean by "dungeon"? Is it shoggoth lairs? The random Darklands structures? The random Abyssal Wasteland structures?
Due to the rather violent changes to terrain in amplified, it's almost guaranteed that anything that generates under specific conditions generate less due to those conditions not being met as much as they would be under normal situations.

**Comment by G1R-Productions** [comment]
The random Abyssal Wasteland structures are spawning so rarely you could spend hours searching for one and never find one. Might I suggest having a configuration option for whether or not the dimensions added by AbyssalCraft mirror the world type of the overworld?
