### ISSUE TITLE
Strength buff from Ethaxium armor is not reset when putting it off

### ISSUE THREAD

**Issue by kutschkem** [Shinoow/AbyssalCraft#39]
The Strength buff is not reset once you don't wear the Ethaxium chestplate anymore. I can complete get rid of all armor but the buff is still there.

**Comment by Shinoow** [comment]
Odd, I'll have to look into this.
Does the effect last if you relog after removing the armor?
Does the effect go away if you drink a bucket of milk after removing the armor?
Does this happen to any other potion effect gained from AbyssalCraft armor?

**Comment by Shinoow** [comment]
Looking deeper into it, the bug is a random occurrence, and can happen to any of the three potion effects that the armor most often deploys (Strength, Regeneration and Saturation). If you continue to wear the armor, the effect will eventually cancel itself out. I could add a little thing that could remove the effect when it's supposed to run out.

**Comment by Shinoow** [comment]
Fixed in 1.8.8
