### ISSUE TITLE
[suggestion] Dynamic Trees Support

### ISSUE THREAD

**Issue by PresquePlayed** [Shinoow/AbyssalCraft#393]
It would be awesome if the dark lands forest biome would be compatible with dynamic trees

**Comment by Shinoow** [comment]
Seems like someone is planning on adding support in their Dynamic Trees addon https://github.com/supermassimo/DynamicTrees-ExC/issues/1 https://github.com/supermassimo/DynamicTrees-ExC/issues/14, so I think I'll leave it to them, since they seem to have the knowhow on adding Dynamic Trees compatibility.
