### ISSUE TITLE
I actually haven't been able to open the mod without minecraft crashing, and I'm not sure why.

### ISSUE THREAD

**Issue by AwesomeKattyK** [Shinoow/AbyssalCraft#394]
### #### Intro:

-----

#### Description:

Crashed before game could even open

#### Crash report:

https://pastebin.com/LLWhF7sw

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: Downloaded from Twitch, the Launcher says 14.23.5.2847
- AbyssalCraft: 1.12.2

#### Latest log file for when the issue was present:

https://pastebin.com/giXPux9q

**Comment by Shinoow** [comment]
Has this happened with any other mod? Or with just Forge alone? Looks a bit like a faulty installation, especially this part:
`Caused by: java.io.FileNotFoundException: C:\Users\Jenna00211\Twitch\Minecraft\Instances\Magic (The system cannot find the file specified)`
Which indicates that the launcher can't find the instance folder.
Also, please upload your crash report and log to pastebin (or any similar service) next time, rather than dumping a wall of text.

**Comment by Shinoow** [comment]
Closing this for now. I think it's more related to the Minecraft (and/or Forge) installation rather than the mod.
