### ISSUE TITLE
Placing Omothol Fire on a block leads to game crash

### ISSUE THREAD

**Issue by RisingInIris2017** [Shinoow/AbyssalCraft#419]
#### Description:
How to reproduce:
1. Get a Omothol Fire item by using JEI.
2. Place it on a block. In my test, I placed it on a vanilla brick block.
3. Game crash.
4. After game crashed, re-enter the saved world.
5. Game still crash.

#### Crash report:
Placed the Omothol Fire, and game crashed instantly, providing this report:
https://paste.dimdev.org/binutuvejo.mccrash
After game crashed, re-entering the game, and game crashed again.
This time I got the crash-report below:
https://paste.dimdev.org/ozizemapep.mccrash

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- AbyssalCraft: 1.9.17

#### Latest log file for when the issue was present:
https://paste.ubuntu.com/p/fmdjsqwYMF/

**Comment by Shinoow** [comment]
I can't find it now, but I believe someone has encountered a similar crash in the past in conjunction to either some optimization mod or CCL. Since you don't have CCL, this might be cause by either VanillaFix, Optifine or Foamfix. Some mod is doing something with block rendering, which in turn leads to a crash with this block.

**Comment by RisingInIris2017** [comment]
Thanks a lot!
If you need deeper testing, you may reply my comment and I will provide as much information as I can.
I cannot figure out what caused the issue too, so your help is indeed needed.
I believe with our cooperation we will finally find out the bug.
Thanks again!
