### ISSUE TITLE
Lessershoggoth crashes the server.

### ISSUE THREAD

**Issue by Kingi-s** [Shinoow/AbyssalCraft#423]
#### Intro:

I just created some of that biomass thing, placed it down and instantly when a lessershoggoth spawns, the server crashes, and when trying to start it again it crashes. I also went back to an backup once, did everything again and the same, it crashes.

edit: updating to the latest abyssalcraft on server and client doesnt do anything about the problem.

#### Description:

It occurss on project ozone 3 modpack, but i dont think the modpack author can do anything about this problem.

#### Crash report:

https://pastebin.com/ScvEVZ8i

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847-universal
- AbyssalCraft: 1.12.2-1.9.17
- AbyssalCraft Integration: 1.12.2-1.9.0

#### Latest log file for when the issue was present:

https://gist.github.com/Kingi-s/1e392f645984ae757e1ab1776b3e717c

**Comment by Shinoow** [comment]
This is caused by ZeroCore. Since the author stopped pushing code to their GitHub repo nearly 4 years ago, I can't dig through their codebase without downloading and decompiling the mod, which I can't really be bothered to do.
Anyways, here's an issue opened at their issue tracker with a similar crash https://github.com/ZeroNoRyouki/ZeroCore/issues/29
