### ISSUE TITLE
Staff of Rending only works after first item

### ISSUE THREAD

**Issue by heater405** [Shinoow/AbyssalCraft#426]
I have an issue with the staff of rending, regardless of how rough it is to progress in this mod, i can't get the staff of rending to work after the first time i get an item from using it. Every time i reach 100 in progress it goes back to zero when i use it again and i get no item. More specifically when I am getting abyssal wasteland essence in the abyssal wasteland dimension. Am I just dumb or is this a problem a lot of people are experiencing in the 1.12.2 version. The mod version is 1.9.19

**Comment by Shinoow** [comment]
This appears to be a bug introduced in 1.9.19, so there wouldn't be that many affected by it _yet_, since the update has only been out for a week. Anyways, I'm gonna put together a hotfix for it, since it requires changing one line of code.
Also, please use the bug report template when reporting bugs in the future.
