### ISSUE TITLE
Server keeps crashing

### ISSUE THREAD

**Issue by Hypnotized123** [Shinoow/AbyssalCraft#442]
Intro:

**Server does not start. I do not know how to reproduce this because I literally did not do anything besides move a IronChest containing a necronomicon and then 3 minutes later the server crashed.**

Description:

**If this bug occurs in a modpack, please report this to the modpack author. Otherwise delete this line and add your description here.**

Crash report:

[Crash Report](https://pastebin.com/qGdCF0iB)
----

Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- AbyssalCraft: 1.10.2

Latest log file for when the issue was present:

[Server Log](https://pastebin.com/A44d69Pb)

**Comment by Shinoow** [comment]
That comment in the crash report prior to the stack trace is spot on. This makes no sense.
If this is happening in conjunction with Iron Chests (rather than that just being a coincidence), maybe try updating that mod, as you're not running the latest version of it?
What I can make out from the crash report is that some block with a tile entity (the tile entity bit isn't mentioned in the stack trace, but there should've been something related to it), which most likely has an inventory, is handling Capabilities incorrectly, resulting in the game crashing. I've had some prior crashes related to the newish Item Transfer System, but this one I'm clueless on.

**Comment by Hypnotized123** [comment]
I will try updating the iron chests mod right now to see if it works... I was also looking through alot of my other reports from yesterday and there seems to be one that has a different reason for a crash however it has nothing to do with abyssal craft, none that I can see anyways. If youd like I can post it here for some insight on what happened? Honestly, its seems like the whole internet in clueless of this one i spent like 5 hours searching up the issue to see what happened :/

**Comment by Shinoow** [comment]
Sure, there could be something in there that hopefully explains why.

**Comment by Hypnotized123** [comment]
Update. The mods I have are now up-to-date according to curseforge. I looked through my logs and crash reports and [here is a crash report](https://pastebin.com/JQ2eSjPh) I found at my time 4:25pm but I could not find a log at that same time...

Is there anyway I can copy my multiplayer world to single player and see if I get the same crash?

**Comment by Shinoow** [comment]
That one seems to be caused by lag through logging, coming from father toast's special mobs.
You can instructions [here](https://www.minecraftforum.net/forums/support/java-edition-support/2455400-how-do-i-convert-a-server-world-into-a-single), but generally check the folder structures and copy the appropriate folders from the server folder to a single player save.

**Comment by Hypnotized123** [comment]
So I did this and same error. I also tried to get in without abysal craft installed and the whole world is corrupted. I don't know if that is because I removed the mod or if that is the reason the world is not letting me log in. 

Let me also further expand on how the issue started. I had iron chests with alot of items from abyssal craft, and I was trying to make a AE2 storage system.  I moved the iron chest (with chest transporter mod), then upgraded the chests to diamond chest (using the upgrades without breaking the chest), then connected them to the AE2 system. About 2 or 3 minutes later the server froze for about a minute and crashed.

**Comment by Shinoow** [comment]
The only thing I can really pinpoint as a potential culprit would be NotEnoughIDs, since that mod is infamous for corrupting worlds due to how it's programmed. An additional problem that mod poses is that your world becomes corrupted if you remove a mod after installing it (which you experienced above).

I don't really see anything in the explanation on how it started that seems out of place enough to cause something like this. The only bet I can place is that NotEnoughIDs caused this.
