### ISSUE TITLE
Config file malfunction: Potion ID's from config dont affect runtime ID's.

### ISSUE THREAD

**Issue by Darkos333** [Shinoow/AbyssalCraft#45]
My current potion config settings for Abyssal Craft look like this:
potions {
    I:Antimatter=59
    I:"Coralium Plague"=100
    I:"Dread Plague"=101
}
However, in-game ID's of these potion effects are:
potion.Cplague = 24
potion.Dplague = 25
potion.Antimatter = 26
Which, as far as I remember, are default values.

**Comment by Shinoow** [comment]
In 1.8.8 I replaced the Potion ID configuration with a dynamic ID assigner. Any unoccupied IDs are selected for the potion effects, eliminating any ID conflicts (as long as another mod loaded after AbyssalCraft doesn't hardcode their potion IDs to any that come directly after the vanilla ID range). Since a user discovered that this kind of conflict happened with IC2, the ID configuration will come back, but for now it won't affect the mod in any way if it's still in the config file.

**Comment by Darkos333** [comment]
Okay, got it. I think that I have some usefull advice in this matter:
Dont remove dynamic ID assigner from your mod, just make an config option to manually disable it.
Its great feature by itself and it would work perfectly fine, if only all mod devs code it this way.

**Comment by Shinoow** [comment]
Yeah, I phrased that wrong. I added a config option to disable it, allowing you to manually set the ID. It was a derp of me to imply that I removed the dynamic IDs alltogether.

**Comment by Shinoow** [comment]
You can see the conversation where I decided to do that at #41
