### ISSUE TITLE
Getting a server crash whenever someone makes a transmutation gem

### ISSUE THREAD

**Issue by Saereth** [Shinoow/AbyssalCraft#52]
Forge 1558
AbyssalCraft 1.7.10 1.8.9.6
Full pack mod listing: http://technicpack.net/modpack/everything-is-hostile.588734/mods

Full crashlog:
http://pastebin.com/QjF8Z0mz

This did not occur in the older version we were running
AbyssalCraft 1.7.10 1.8.8b

It doesnt -always- happen though from what he said. The player was able to make 3 gems and the 4th crashed the server. After restart same thing, he made 2 then crashed.

**Comment by Shinoow** [comment]
That's caused by a null check I forgot to implement in 1.8.9.6. Updating to 1.9.0a or 1.9.0b will fix it. I would suggest 1.9.0b, as it is more feature-complete than 1.9.0a.

**Comment by Saereth** [comment]
np we'll update today I just tend to avoid betas on our live server, thanks for the quick response!

**Comment by Shinoow** [comment]
Technically that version shouldn't be labeled as a beta (nor should the alpha be labeled as an alpha). Theyr'e both incredibly stable, with nothing available that can cause corruptions or crashes in general. The labeling is due to them lacking a whole bunch of features planned to be released with AC 1.9.0, leaving them with alpha and beta tags.
