### ISSUE TITLE
Crash on loading mods. Incompatibility?

### ISSUE THREAD

**Issue by Ctakep** [Shinoow/AbyssalCraft#524]
#### Crash report:

https://pastebin.com/7kF76qmR

#### Affected versions 

- Minecraft: 1.12.2
- Forge: 14.23.5.2859
- AbyssalCraft: 2.0.0 Alpha

#### Latest log file for when the issue was present:
(pastebin wouldn't let me generate a link so I could only 
[latest.log](https://github.com/user-attachments/files/17355212/latest.log)
send the file)

**Comment by Shinoow** [comment]
Seems like something has changed in the code of Ice and Fire, but I can't find the version specified in the crash report (2.0.2).
Try downgrading that mod (seems like 1.9.1 is the latest on the [curseforge page](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/2939529)).
I can also warn ahead that the game will crash with AbyssalCraft Integrations installed, since it doesn't have support for the 2.0.0 branch of AbyssalCraft.
