### ISSUE TITLE
[1.9] Client-side crash

### ISSUE THREAD

**Issue by kwpugh** [Shinoow/AbyssalCraft#86]
Crash report: http://pastebin.com/raw/5sCVjV1L

Forge 1865
Mod: AbyssalCraft-1.9-1.9.1.4.jar

Crash while walking

I'm going to have to remove your mod until this is fixed.  The crashes are becoming quite widespread and often.

**Comment by Shinoow** [comment]
I've found no way to reproduce this crash at all, but I've compiled a test build that should stop it from happening at all. If you still crash while running that version, then the Forge event itself is broken, because I've taken all necessary measures to ensure there are no null variables. Due to Github not allowing me to attach a jar file, I've placed the jar file inside a zip.
[test build.zip](https://github.com/Shinoow/AbyssalCraft/files/245937/test.build.zip)

**Comment by kwpugh** [comment]
I certainly appreciate all the effort you have put into trying to isolate the bug.   I will give this build a try on the server and let you know.   I had to remove Waila all together from the mix because it has become unstable.

Thank you,

Kevin

**Comment by PlacidK** [comment]
I've also had client crashes on my server.
My son had a few when running/flying arround and bumping into snow and grass. I crashed when i bumped into a cable from refined storage mod. 

I'll try the test build too in a few mins.

**Comment by EnderT5** [comment]
same crash happened to me (im dreaming about ''no crashing abyssalcraft'' now)

http://pastebin.com/L8VqdktX

**Comment by PlacidK** [comment]
Sofar i've had no abyssalcraft-related crashes on my server with this test build. :D

**Comment by kwpugh** [comment]
Reporting in:  We have not experienced any crashes with the test build either.

**Comment by Shinoow** [comment]
So it seems to be working. Good. I'll have a full release of version 1.9.1.5 out tomorrow (working on new tree designs, kinda want them to be finished before the release).
