### ISSUE TITLE
Darklands oak sapling bug

### ISSUE THREAD

**Issue by Plurp13** [Shinoow/AbyssalCraft#91]
I'm having a weird and sad issue with the saplings from the awesome trees in the darklands forest. I planted them in a different biome and they turned into regular oaks when they grew, I thought it was just cuz they could only grow properly in the darklands so I saved what I could and planted them there. In several hours only one grew and it still turned into a regular oak. Is this intended behavior or are the saplings bugged? I'll be really sad if that's how they're supposed to work cuz that's the coolest wood ever I need it to be renewable T_T

**Comment by Shinoow** [comment]
That's not supposed to happen...
Can you tell me which Minecraft version, Forge version and AbyssalCraft version you're using?

**Comment by Plurp13** [comment]
It's probably an old one actually maybe it's already fixed...it's in a modpack ^_^; version 1.9.1.1

**Comment by Shinoow** [comment]
Well, the thing is, there's never been a case where the Darklands Oak Sapling would create an ordinary oak tree... The tree itself was originally implemented in the 7th release (for Minecraft 1.4.6), and has had the same appearance ever since (well until AC 1.9.1.5, where I implemented a new design, making them stand out quite a lot from vanilla trees).
The only logical thing I guess might've happened here is that you perhaps cut down a regular oak tree (as any vanilla tree found in Darklands biomes have the exact same color on their leaves, just as the foliage of regular grass also changes), which would explain why the sapling grew into a regular oak. If that's not the case, then the only thing I can think of next would be if another mod has something to do with this (like if there's a mod that replaces all trees with a specific one when any sapling is grown).

**Comment by Plurp13** [comment]
It was definitely the darklands one. The sapling is purple and the tree I got them from has purple animated bark. Maybe it's another mod in the pack. I guess I should ask the person who made the pack about it not you huh? Although it's also weird that now they're not growing at all. Are they meant to take ages to grow?

**Comment by Plurp13** [comment]
Oh and I'm in mc 1.8 with the latest forge, forgot you asked for that too.

**Comment by Shinoow** [comment]
I seem to have found the root of this. Apparently there's 2 methods used in the Sapling class to prepare the sapling to eventually grow into a tree. The thing is, both of them use the same 4 parameters, but one is pretty much never called (and this is the one I was overriding in my saplings), leading to the other one being called instead (and this leads to a regular oak growing instead of any of my trees).
The growing procedure should be identical to vanilla trees, so I'm not sure what could be slowing it down.

**Comment by Plurp13** [comment]
Weird. I'll try bonemealing some of them and breaking and replanting some others. At least we know why they grew oaks though! So does that mean they've just got a really small chance to be the proper tree or will they always grow oaks because of the weird parameters thing?

**Comment by Shinoow** [comment]
Unless some random stuff happen out of nowhere, they will most likely grow into regular oaks.

**Comment by Plurp13** [comment]
Dang that's unfortunate, I guess I'll just have to be sparing with my use of the awesome logs. Thanks.

**Comment by Shinoow** [comment]
Sorry, phrased that wrongly! They will grow into oaks if allowed to grow by themselves, but will always turn into the right tree when bonemealed.

**Comment by Plurp13** [comment]
Oh! Ok, that's good, we have tons of bones I think that's doable. Thank you ^.^
